import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import vercel from '@astrojs/vercel/serverless';
import sitemap from '@astrojs/sitemap';

// ============================================
// Security Headers — Content Security Policy
// Protects against XSS, clickjacking, MITM, etc.
// ============================================
const securityHeaders = [
  {
    key: 'Content-Security-Policy',
    value: [
      "default-src 'self'",
      // Allow inline scripts/styles (Astro & Vite inject these at runtime)
      "script-src 'self' 'unsafe-inline' https://challenges.cloudflare.com",
      "style-src 'self' 'unsafe-inline'",
      // Images: allow any HTTPS (video thumbnails from YouTube/TikTok)
      "img-src 'self' data: https: blob:",
      // Media: allow video/audio streaming
      "media-src 'self' https: blob:",
      // Connect: allow Supabase + our Worker + Turnstile + YouTube embed
      "connect-src 'self' https://*.supabase.co https://*.workers.dev https://challenges.cloudflare.com https://www.youtube.com",
      // Frames: allow YouTube embed + Turnstile widget
      "frame-src https://www.youtube.com https://challenges.cloudflare.com",
      // Fonts: only self-hosted
      "font-src 'self'",
      // Block plugins, objects
      "object-src 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "frame-ancestors 'none'",
      // Force HTTPS
      "upgrade-insecure-requests",
    ].join('; '),
  },
  {
    key: 'X-Content-Type-Options',
    value: 'nosniff',
  },
  {
    key: 'X-Frame-Options',
    value: 'DENY',
  },
  {
    key: 'Referrer-Policy',
    value: 'strict-origin-when-cross-origin',
  },
  {
    key: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=(), payment=(), interest-cohort=()',
  },
  {
    key: 'Strict-Transport-Security',
    value: 'max-age=31536000; includeSubDomains; preload',
  },
  {
    key: 'X-XSS-Protection',
    value: '1; mode=block',
  },
];

// https://astro.build/config
export default defineConfig({
  site: 'https://unduhaja.vercel.app',
  output: 'server',
  adapter: vercel({
    imageService: true,
    webAnalytics: { enabled: false },
  }),
  integrations: [
    react(),
    sitemap({
      i18n: {
        defaultLocale: 'id',
        locales: {
          id: 'id-ID',
          en: 'en-US',
        },
      },
      // Add lastmod to all URLs (Google prefers fresh sitemaps)
      lastmod: new Date(),
      // Custom filter to exclude API routes
      filter: (page) => !page.includes('/api/'),
      // Custom serialize to add priority and changefreq
      serialize(item) {
        if (item.url.includes('/blog/')) {
          item.changefreq = 'weekly';
          item.priority = 0.8;
        } else if (item.url.endsWith('/id/') || item.url.endsWith('/en/')) {
          item.changefreq = 'daily';
          item.priority = 1.0;
        } else if (item.url.includes('/faq') || item.url.includes('/docs') || item.url.includes('/guides')) {
          item.changefreq = 'monthly';
          item.priority = 0.7;
        } else if (item.url.includes('/privacy') || item.url.includes('/terms') || item.url.includes('/dmca')) {
          item.changefreq = 'yearly';
          item.priority = 0.3;
        } else {
          item.changefreq = 'monthly';
          item.priority = 0.6;
        }
        return item;
      },
    }),
  ],
  vite: {
    ssr: {
      noExternal: ['@supabase/ssr', '@supabase/supabase-js'],
    },
  },
  image: {
    service: {
      entrypoint: 'astro/assets/services/sharp',
    },
  },
  prefetch: {
    prefetchAll: true,
    defaultStrategy: 'viewport',
  },
  // Apply security headers to all responses
  // Vercel reads these via vercel.json (auto-generated by adapter)
  // Astro also supports `headers` in route config, but global via middleware is cleaner
});
